// Client review portal: one self-contained HTML file with every planned post, its slides
// and caption. Shared by email or WhatsApp; opens in any browser with no login.
// Every piece of text is escaped; the file contains no scripts.
import { escapeHtml as e } from './escape.js'
import { visionDataUrl } from '../data/media.js'
import { publishImageIds, postNumber, hashtagList, formatLabel } from '../data/model.js'
import { mapLimit } from './pool.js'

export function portalStats(doc) {
  const posts = doc.posts.filter((p) => p.slides.length || p.design?.exportImageId)
  return {
    posts: posts.length,
    approved: posts.filter((p) => p.approved).length,
    captioned: posts.filter((p) => p.caption?.text?.trim()).length,
  }
}

export async function buildPortal(doc, { handle = '', onProgress, signal } = {}) {
  const posts = doc.posts
    .map((p, i) => ({ p, n: postNumber(doc.posts, i) }))
    .filter(({ p }) => p.slides.length || p.design?.exportImageId)
  const ids = [...new Set(posts.flatMap(({ p }) => publishImageIds(p).slice(0, 5)))]
  const urls = new Map()
  let done = 0
  await mapLimit(ids, 3, async (id) => {
    urls.set(id, await visionDataUrl(id, 1080))
    done += 1
    onProgress?.(done, ids.length)
  }, { signal })

  const cards = posts.map(({ p, n }) => {
    const imgs = publishImageIds(p).filter((id) => urls.has(id))
    const cover = imgs[0] ? `<div class="cover"><img src="${urls.get(imgs[0])}" alt=""></div>` : '<div class="cover empty"></div>'
    const strip = imgs.length > 1
      ? `<div class="strip">${imgs.slice(1, 5).map((id) => `<img src="${urls.get(id)}" alt="">`).join('')}</div>`
      : ''
    const tags = hashtagList(p.caption?.hashtags).join(' ')
    const caption = p.caption?.text?.trim()
      ? `<p class="caption">${e(p.caption.text)}</p>`
      : '<p class="caption pending">Caption pending</p>'
    const type = formatLabel(p.format) + (p.slides.length > 1 ? ` · ${p.slides.length} slides` : '')
    return `<article class="card">
  <header><span class="num">Post #${n}</span><span class="type">${e(type)}</span>${p.approved ? '<span class="badge">Approved</span>' : ''}</header>
  ${cover}${strip}
  <div class="body">${caption}${tags ? `<p class="tags">${e(tags)}</p>` : ''}</div>
</article>`
  }).join('\n')

  const date = new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Content Review — ${e(handle)}</title>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;500&family=DM+Sans:wght@300;400;500&family=DM+Mono:wght@400&display=swap">
<style>
*{box-sizing:border-box;margin:0;padding:0}
body{background:#0F0F0F;color:#F0EDE8;font-family:'DM Sans',sans-serif;font-size:14px;line-height:1.6}
.top{position:sticky;top:0;background:rgba(15,15,15,.94);border-bottom:1px solid #2C2C2C;padding:18px 24px;backdrop-filter:blur(8px);z-index:2}
.top h1{font-family:'Playfair Display',serif;font-weight:500;font-size:22px;letter-spacing:.04em}
.top p{font-family:'DM Mono',monospace;font-size:10px;letter-spacing:.18em;color:#8A8682;margin-top:2px}
main{max-width:960px;margin:0 auto;padding:28px 20px 60px;display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:20px}
.card{background:#1A1A1A;border:1px solid #2C2C2C;border-radius:8px;overflow:hidden}
.card header{display:flex;gap:8px;align-items:center;padding:12px 14px;font-size:12px}
.num{font-weight:500}.type{color:#8A8682}
.badge{margin-left:auto;background:rgba(90,138,106,.18);color:#8FC29F;border-radius:4px;padding:2px 8px;font-size:11px}
.cover{aspect-ratio:4/5;background:#151515}.cover img{width:100%;height:100%;object-fit:cover;display:block}
.strip{display:grid;grid-template-columns:repeat(4,1fr);gap:2px;padding:2px}.strip img{width:100%;aspect-ratio:1;object-fit:cover;display:block}
.body{padding:14px}.caption{white-space:pre-wrap}.pending{color:#6B6762;font-style:italic}
.tags{margin-top:10px;font-family:'DM Mono',monospace;font-size:11px;color:#B8B4AE}
footer{text-align:center;color:#6B6762;font-size:11px;padding:0 20px 40px}
@media (max-width:600px){main{grid-template-columns:1fr}}
</style></head>
<body>
<div class="top"><h1>KSS</h1><p>KSHETEJ SAREEN STUDIOS · CONTENT REVIEW</p></div>
<main>
${cards}
</main>
<footer>Generated by Kshetej Sareen Studios · ${e(date)}</footer>
</body></html>`
}

export const portalFilename = () => `KSS-Client-Review-${Date.now()}.html`
