import { useState } from 'react'
import { useStore } from '../store.jsx'

// Generates a self-contained HTML page the client can view
function generateClientHTML(plan, images, context, handle) {
  const imgByIdx = (idx) => {
    if (!idx || idx < 1 || idx > images.length) return null
    return images[idx - 1]
  }

  const filledPosts = plan.filter(p => p.imageIndex)

  const postsHTML = filledPosts.map((p, i) => {
    const img = imgByIdx(p.imageIndex)
    const igNum = plan.length - plan.indexOf(p)
    const slides = (p.slides || []).map(idx => imgByIdx(idx)).filter(Boolean)

    return `
    <div class="post-card">
      <div class="post-header">
        <span class="post-num">Post #${igNum}</span>
        <span class="post-type">${p.type}${slides.length > 1 ? ` · ${slides.length} slides` : ''}</span>
        ${p.captionApproved ? '<span class="approved-badge">✓ Approved</span>' : ''}
      </div>
      <div class="post-body">
        <div class="post-images">
          ${slides.slice(0,4).map((sImg, si) => `
            <div class="post-image ${si === 0 ? 'cover' : 'slide'}">
              <img src="${sImg.dataUrl}" alt="Slide ${si + 1}"/>
              ${si === 0 && slides.length > 1 ? `<div class="slide-count">1/${slides.length}</div>` : ''}
            </div>
          `).join('')}
        </div>
        <div class="post-caption">
          ${p.caption ? `<p class="caption-text">${p.caption}</p>` : '<p class="no-caption">Caption pending</p>'}
          ${p.firstComment ? `<p class="hashtags">${p.firstComment}</p>` : ''}
        </div>
      </div>
    </div>`
  }).join('')

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<title>Content Review — ${handle}</title>
<link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;500&family=DM+Sans:wght@300;400;500&family=DM+Mono:wght@300;400&display=swap" rel="stylesheet"/>
<style>
  *{box-sizing:border-box;margin:0;padding:0}
  body{background:#0F0F0F;color:#F0EDE8;font-family:'DM Sans',sans-serif;min-height:100vh;padding:0 0 60px}
  .header{padding:32px 24px 24px;border-bottom:1px solid #2C2C2C;background:#0F0F0F;position:sticky;top:0;z-index:10}
  .logo{font-family:'Playfair Display',serif;font-size:22px;font-weight:500;color:#F0EDE8;margin-bottom:4px}
  .sub{font-size:11px;color:#6B6762;font-family:'DM Mono',monospace;letter-spacing:.1em}
  .brief{font-size:11px;color:#C0C0C8;margin-top:8px;font-family:'DM Mono',monospace}
  .grid{max-width:960px;margin:32px auto;padding:0 24px;display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:20px}
  .post-card{background:#1A1A1A;border:1px solid #2C2C2C;border-radius:8px;overflow:hidden}
  .post-header{display:flex;align-items:center;gap:8px;padding:10px 14px;border-bottom:1px solid #2C2C2C}
  .post-num{font-size:10px;color:#C0C0C8;font-family:'DM Mono',monospace;font-weight:500}
  .post-type{font-size:9px;color:#6B6762;font-family:'DM Mono',monospace;text-transform:uppercase;letter-spacing:.08em;flex:1}
  .approved-badge{font-size:9px;padding:2px 8px;border-radius:10px;background:rgba(90,138,106,.2);color:#5A8A6A;border:1px solid #5A8A6A;font-family:'DM Mono',monospace}
  .post-body{padding:14px}
  .post-images{display:flex;gap:4px;margin-bottom:12px}
  .post-image{flex:1;border-radius:4px;overflow:hidden;position:relative}
  .post-image.cover{flex:2}
  .post-image img{width:100%;aspect-ratio:4/5;object-fit:cover;display:block}
  .post-image.slide img{aspect-ratio:1}
  .slide-count{position:absolute;top:6px;right:6px;background:rgba(0,0,0,.65);color:#fff;font-size:9px;padding:2px 6px;border-radius:8px;font-family:'DM Mono',monospace}
  .caption-text{font-size:12px;line-height:1.65;color:#B8B4AE;white-space:pre-wrap}
  .no-caption{font-size:11px;color:#4A4744;font-style:italic}
  .hashtags{font-size:9px;color:#888892;font-family:'DM Mono',monospace;margin-top:8px;line-height:1.6}
  .footer{text-align:center;padding:40px 24px 0;font-size:10px;color:#4A4744;font-family:'DM Mono',monospace}
  @media(max-width:600px){.grid{grid-template-columns:1fr;padding:0 16px}}
</style>
</head>
<body>
<div class="header">
  <div class="logo">KSS</div>
  <div class="sub">KSHETEJ SAREEN STUDIOS · CONTENT REVIEW</div>
  ${context ? `<div class="brief">${context}</div>` : ''}
</div>
<div class="grid">${postsHTML}</div>
<div class="footer">Generated by Kshetej Sareen Studios · ${new Date().toLocaleDateString('en-IN',{day:'numeric',month:'long',year:'numeric'})}</div>
</body>
</html>`
}

export default function ClientPortal({ onClose, showToast }) {
  const { state } = useStore()
  const [downloading, setDownloading] = useState(false)

  const filledPosts = state.plan.filter(p => p.imageIndex)
  const approvedCount = filledPosts.filter(p => p.captionApproved).length

  const downloadPortal = () => {
    setDownloading(true)
    try {
      const html = generateClientHTML(
        state.plan,
        state.images,
        state.globalContext,
        state.settings.handle || '@kshetejsareenstudios'
      )
      const blob = new Blob([html], { type: 'text/html' })
      const a = document.createElement('a')
      a.href = URL.createObjectURL(blob)
      a.download = `KSS-Client-Review-${Date.now()}.html`
      a.click()
      showToast('Client review file downloaded ✓ — share via email or WhatsApp')
    } catch(e) {
      showToast('Error: ' + e.message)
    } finally {
      setDownloading(false)
    }
  }

  return (
    <div style={{ position: 'fixed', inset: 0, zIndex: 1000, background: 'rgba(0,0,0,.85)', display: 'flex', alignItems: 'center', justifyContent: 'center', backdropFilter: 'blur(8px)' }}
      onClick={e => e.target === e.currentTarget && onClose()}>
      <div style={{ background: 'var(--surface)', border: '1px solid var(--border2)', borderRadius: 12, padding: 32, maxWidth: 480, width: '90%', boxShadow: 'var(--shadow-lg)' }}>

        <div style={{ fontFamily: 'var(--font-display)', fontSize: 22, fontWeight: 500, marginBottom: 6 }}>Client Review Portal</div>
        <div style={{ fontSize: 12, color: 'var(--mute)', marginBottom: 24 }}>Generate a beautiful HTML file your client can open in any browser</div>

        {/* Stats */}
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gap: 12, marginBottom: 24 }}>
          {[
            ['Posts', filledPosts.length],
            ['Captioned', filledPosts.filter(p => p.caption).length],
            ['Approved', approvedCount],
          ].map(([label, val]) => (
            <div key={label} style={{ padding: 16, background: 'var(--surface2)', borderRadius: 8, textAlign: 'center', border: '1px solid var(--border)' }}>
              <div style={{ fontFamily: 'var(--font-display)', fontSize: 28, fontWeight: 500, color: 'var(--text)' }}>{val}</div>
              <div style={{ fontSize: 9, color: 'var(--mute)', fontFamily: 'var(--font-mono)', textTransform: 'uppercase', letterSpacing: '.1em', marginTop: 3 }}>{label}</div>
            </div>
          ))}
        </div>

        {/* What's included */}
        <div style={{ padding: '12px 16px', background: 'var(--surface2)', borderRadius: 8, marginBottom: 24, border: '1px solid var(--border)' }}>
          <div style={{ fontSize: 10, color: 'var(--silver)', fontFamily: 'var(--font-mono)', marginBottom: 8, letterSpacing: '.1em', textTransform: 'uppercase' }}>Included in review</div>
          {['All assigned post images', 'Carousel slides (up to 4 shown)', 'Captions and hashtags', 'Approval status', 'Brand context header'].map(item => (
            <div key={item} style={{ fontSize: 11, color: 'var(--text2)', marginBottom: 4 }}>· {item}</div>
          ))}
        </div>

        <div style={{ display: 'flex', gap: 10 }}>
          <button className="btn btn-ghost" style={{ flex: 1 }} onClick={onClose}>Cancel</button>
          <button className="btn btn-primary" style={{ flex: 2 }} onClick={downloadPortal} disabled={downloading || !filledPosts.length}>
            {downloading ? <><span className="spin" /> Generating…</> : '↓ Download Client Review'}
          </button>
        </div>

        <div style={{ marginTop: 12, fontSize: 10, color: 'var(--mute)', textAlign: 'center', fontFamily: 'var(--font-mono)' }}>
          Share the HTML file via email, WhatsApp, or Dropbox — no login needed
        </div>
      </div>
    </div>
  )
}
